### PR TITLE
DSD-2248: Allow users to specify custom metadata

### PR DESCRIPTION
**Pull request by creynolds15**

### CODE REVIEW

**Comment by tamr-github-integrator** [comment]
# [tfsec] Results
## Failed: 9 issue(s)
| # | ID | Severity | Title | Location | Description |
|---|----|----------|-------|----------|-------------|
| 1 | `google-compute-enable-shielded-vm-im` | *MEDIUM* | _Instances should have Shielded VM integrity monitoring enabled_ | `main.tf:43-100` | Instance does not have shielded VM integrity monitoring enabled. |
| 2 | `google-compute-enable-shielded-vm-vtpm` | *MEDIUM* | _Instances should have Shielded VM VTPM enabled_ | `main.tf:43-100` | Instance does not have VTPM for shielded VMs enabled. |
| 3 | `google-compute-no-project-wide-ssh-keys` | *MEDIUM* | _Disable project-wide SSH keys for all instances_ | `main.tf:43-100` | Instance allows use of project-level SSH keys. |
| 4 | `google-compute-vm-disk-encryption-customer-key` | *LOW* | _VM disks should be encrypted with Customer Supplied Encryption Keys_ | `main.tf:50-56` | Instance disk encryption does not use a customer managed key. |
| 5 | `google-compute-enable-shielded-vm-im` | *MEDIUM* | _Instances should have Shielded VM integrity monitoring enabled_ | `main.tf:43-100` | Instance does not have shielded VM integrity monitoring enabled. |
| 6 | `google-compute-enable-shielded-vm-vtpm` | *MEDIUM* | _Instances should have Shielded VM VTPM enabled_ | `main.tf:43-100` | Instance does not have VTPM for shielded VMs enabled. |
| 7 | `google-compute-no-default-service-account` | *CRITICAL* | _Instances should not use the default service account_ | `main.tf:79` | Instance uses the default service account. |
| 8 | `google-compute-no-project-wide-ssh-keys` | *MEDIUM* | _Disable project-wide SSH keys for all instances_ | `main.tf:43-100` | Instance allows use of project-level SSH keys. |
| 9 | `google-compute-vm-disk-encryption-customer-key` | *LOW* | _VM disks should be encrypted with Customer Supplied Encryption Keys_ | `main.tf:50-56` | Instance disk encryption does not use a customer managed key. |

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Comment by tamr-github-integrator** [comment]
_No problems detected!_

**Review by souza-dan — APPROVED** [review]
LGTM

**Pull request merged**
